# Generated by Django 6.0.7 on 2026-07-09 09:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('type', models.CharField(default='Mixed', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('hourlyRate', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
                ('bikeHourlyRate', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('carHourlyRate', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
                ('totalCapacity', models.IntegerField(default=100)),
                ('bikeCapacity', models.IntegerField(default=30)),
                ('carCapacity', models.IntegerField(default=70)),
                ('availableBike', models.IntegerField(default=30)),
                ('availableCar', models.IntegerField(default=70)),
                ('walkingTime', models.IntegerField(default=3)),
                ('indicator', models.CharField(choices=[('green', 'Green'), ('red', 'Red')], default='green', max_length=10)),
                ('priority', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slotLabel', models.CharField(max_length=50)),
                ('vehicleNumber', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(default='Car', max_length=10)),
                ('venue', models.CharField(max_length=100)),
                ('hours', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(default='QR Code', max_length=50)),
                ('paymentDetails', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('ticketCode', models.CharField(max_length=100, unique=True)),
                ('qrCode', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('startsAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.parkingslot')),
            ],
        ),
    ]
